import type { NextPage } from "next";
import Head from "next/head";
import { DashboardAnalytics } from "components/Dashboard";
import { useEffect } from "react";
import { useNavContext } from "contexts/NavContext";
import { TbPresentationAnalytics } from "react-icons/tb";

const Home: NextPage = () => {
  const { setActive } = useNavContext();
  useEffect(() => {
    setActive("Dashboard");
  }, []);
  return (
    <div>
      <Head>
        <title>Mainstack Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" py-4 px-4 sm:px-8 md:px-[60px] ">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-bold text-xl md:text-2xl mb-[10px] text-black-300 ">
              Good morning, Blessing ⛅️
            </h1>
            <h3 className="text-gray-500 text-xs md:text-sm font-medium">
              Check out your dashboard summary.
            </h3>
          </div>

          <p className="text-primary text-sm font-semibold hidden sm:block">
            View analytics
          </p>
          <TbPresentationAnalytics className="sm:hidden text-2xl text-primary cursor-pointer" />
        </div>

        <div className="mt-5">
          <DashboardAnalytics />
        </div>
      </div>
    </div>
  );
};

export default Home;
